name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, release
      run: |
        npm ci
        npm run release
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
